### ISSUE TITLE
keep previous state of 'ruler is visible' after plugin shows none

### ISSUE THREAD

**Issue by Alexey-T** [ildarkhasanshin/cuda_fold_ruler#2]

**Comment by ildarkhasanshin** [comment]
https://github.com/ildarkhasanshin/cuda_fold_ruler/commit/499ae18d0ee3ba71622526358fb7e100d1fe9d9a

не пойму как подправить, чтоб корректно считывался `self.ruler_init` после рестарта

**Comment by Alexey-T** [comment]
может даватьь по умолчанию None и при первой активации текста считывать ed.get_prop, если стояло None ?
